blank_issues_enabled: false
contact_links:
  - name: OJP Cookbook
    url: https://opentransportdata.swiss/en/cookbook/open-journey-planner-ojp/
    about: OJP current implementation status (opentransportdata.swiss link)
