name: Incident
description: Report a problem or issue
title: "[Bug]: "
labels:
  - bug

body:
  - type: input
    id: issue_title
    attributes:
      label: Issue title
      description: Short summary of the issue
    validations:
      required: true

  - type: input
    id: organisation
    attributes:
      label: Organisation
      placeholder: SBB / BLS / ZVV / other
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: Stage
      options:
        - PROD
        - INT
        - TEST
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - OJP v2
        - OJP v1
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the issue in detail
      placeholder: |
        What happened?
        What did you expect?
        Steps to reproduce ...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code / Logs
      description: Paste relevant XML request / response
      render: shell
      placeholder: |
        XML Request / Response
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag & drop screenshots or paste images here
      placeholder: Attach screenshots if relevant
    validations:
      required: false
